application:
  kafka:
    topic: sent_orders

server:
  port: 8082

spring:
  kafka:
    consumer:
      auto-offset-reset: latest
      bootstrap-servers: localhost:9092
      group-id: MyGroup_shipment

    producer:
      bootstrap-servers: localhost:9092